// Package beamdapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package beamdapi

// Defines values for CustomDomainRefCertMode.
const (
	CustomDomainRefCertModeDelegated CustomDomainRefCertMode = "delegated"
	CustomDomainRefCertModeOnDemand  CustomDomainRefCertMode = "on_demand"
)

// Valid indicates whether the value is a known member of the CustomDomainRefCertMode enum.
func (e CustomDomainRefCertMode) Valid() bool {
	switch e {
	case CustomDomainRefCertModeDelegated:
		return true
	case CustomDomainRefCertModeOnDemand:
		return true
	default:
		return false
	}
}

// Defines values for RequestEventOutcome.
const (
	BackendError RequestEventOutcome = "backend_error"
	ClientClosed RequestEventOutcome = "client_closed"
	InProgress   RequestEventOutcome = "in_progress"
	NoRoute      RequestEventOutcome = "no_route"
	Ok           RequestEventOutcome = "ok"
	SizeLimit    RequestEventOutcome = "size_limit"
	Timeout      RequestEventOutcome = "timeout"
)

// Valid indicates whether the value is a known member of the RequestEventOutcome enum.
func (e RequestEventOutcome) Valid() bool {
	switch e {
	case BackendError:
		return true
	case ClientClosed:
		return true
	case InProgress:
		return true
	case NoRoute:
		return true
	case Ok:
		return true
	case SizeLimit:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for ResolveHostResponseCertMode.
const (
	ResolveHostResponseCertModeDelegated ResolveHostResponseCertMode = "delegated"
	ResolveHostResponseCertModeOnDemand  ResolveHostResponseCertMode = "on_demand"
)

// Valid indicates whether the value is a known member of the ResolveHostResponseCertMode enum.
func (e ResolveHostResponseCertMode) Valid() bool {
	switch e {
	case ResolveHostResponseCertModeDelegated:
		return true
	case ResolveHostResponseCertModeOnDemand:
		return true
	default:
		return false
	}
}

// Defines values for ScopeHostnamesResponseShape.
const (
	Flat      ScopeHostnamesResponseShape = "flat"
	Hyphen    ScopeHostnamesResponseShape = "hyphen"
	Subdomain ScopeHostnamesResponseShape = "subdomain"
)

// Valid indicates whether the value is a known member of the ScopeHostnamesResponseShape enum.
func (e ScopeHostnamesResponseShape) Valid() bool {
	switch e {
	case Flat:
		return true
	case Hyphen:
		return true
	case Subdomain:
		return true
	default:
		return false
	}
}

// Defines values for VerifyTokenResponseKind.
const (
	Key     VerifyTokenResponseKind = "key"
	Session VerifyTokenResponseKind = "session"
)

// Valid indicates whether the value is a known member of the VerifyTokenResponseKind enum.
func (e VerifyTokenResponseKind) Valid() bool {
	switch e {
	case Key:
		return true
	case Session:
		return true
	default:
		return false
	}
}

// BeamAuthDiscovery defines model for BeamAuthDiscovery.
type BeamAuthDiscovery struct {
	DeviceCodeUrl   string `json:"device_code_url"`
	TokenUrl        string `json:"token_url"`
	VerificationUri string `json:"verification_uri"`
}

// CreateTokenInput defines model for CreateTokenInput.
type CreateTokenInput struct {
	Label *string `json:"label,omitempty"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CreatedAt string  `json:"createdAt"`
	Id        string  `json:"id"`
	Label     *string `json:"label"`
	Token     string  `json:"token"`
}

// CustomDomainRef defines model for CustomDomainRef.
type CustomDomainRef struct {
	CertMode CustomDomainRefCertMode `json:"cert_mode"`
	Domain   string                  `json:"domain"`
	Primary  bool                    `json:"primary"`
}

// CustomDomainRefCertMode defines model for CustomDomainRef.CertMode.
type CustomDomainRefCertMode string

// DeviceCodeResponse defines model for DeviceCodeResponse.
type DeviceCodeResponse struct {
	DeviceCode      string  `json:"device_code"`
	ExpiresIn       int     `json:"expires_in"`
	Interval        *int    `json:"interval,omitempty"`
	UserCode        string  `json:"user_code"`
	VerificationUri *string `json:"verification_uri,omitempty"`
}

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	DeviceCode string `json:"device_code"`
}

// DeviceTokenResponse defines model for DeviceTokenResponse.
type DeviceTokenResponse struct {
	AccessToken *string     `json:"access_token,omitempty"`
	Edge        *string     `json:"edge,omitempty"`
	Error       *string     `json:"error,omitempty"`
	Scopes      *[]ScopeRef `json:"scopes,omitempty"`
}

// RequestAccepted defines model for RequestAccepted.
type RequestAccepted struct {
	Accepted int  `json:"accepted"`
	Ok       bool `json:"ok"`
}

// RequestBatch defines model for RequestBatch.
type RequestBatch struct {
	Events []RequestEvent `json:"events"`
}

// RequestEvent defines model for RequestEvent.
type RequestEvent struct {
	BytesIn      int                 `json:"bytes_in"`
	BytesOut     int                 `json:"bytes_out"`
	ClientIp     *string             `json:"client_ip,omitempty"`
	ConnectionId *string             `json:"connection_id,omitempty"`
	EndedAt      string              `json:"ended_at"`
	Host         string              `json:"host"`
	IsWebsocket  bool                `json:"is_websocket"`
	Method       string              `json:"method"`
	Outcome      RequestEventOutcome `json:"outcome"`
	Path         *string             `json:"path,omitempty"`
	Referer      *string             `json:"referer,omitempty"`
	RequestId    string              `json:"request_id"`
	Slug         *string             `json:"slug,omitempty"`
	StartedAt    string              `json:"started_at"`
	Status       int                 `json:"status"`
	TtfbMs       *int                `json:"ttfb_ms,omitempty"`
	UserAgent    *string             `json:"user_agent,omitempty"`
}

// RequestEventOutcome defines model for RequestEvent.Outcome.
type RequestEventOutcome string

// ResolveHostResponse defines model for ResolveHostResponse.
type ResolveHostResponse struct {
	CertMode *ResolveHostResponseCertMode `json:"cert_mode,omitempty"`
	Slug     string                       `json:"slug"`
	Tunnel   *string                      `json:"tunnel,omitempty"`
}

// ResolveHostResponseCertMode defines model for ResolveHostResponse.CertMode.
type ResolveHostResponseCertMode string

// RevokeResult defines model for RevokeResult.
type RevokeResult struct {
	Id      string `json:"id"`
	Revoked bool   `json:"revoked"`
}

// ScopeHostnamesResponse defines model for ScopeHostnamesResponse.
type ScopeHostnamesResponse struct {
	Domains     []CustomDomainRef           `json:"domains"`
	PrimaryHost string                      `json:"primary_host"`
	PrimarySlug string                      `json:"primary_slug"`
	Shape       ScopeHostnamesResponseShape `json:"shape"`
	Slugs       []string                    `json:"slugs"`
}

// ScopeHostnamesResponseShape defines model for ScopeHostnamesResponse.Shape.
type ScopeHostnamesResponseShape string

// ScopeRef defines model for ScopeRef.
type ScopeRef struct {
	Role *string `json:"role,omitempty"`
	Slug string  `json:"slug"`
}

// ScopesResponse defines model for ScopesResponse.
type ScopesResponse struct {
	Scopes []ScopeRef `json:"scopes"`
	User   *string    `json:"user,omitempty"`
}

// Token defines model for Token.
type Token struct {
	CreatedAt  string  `json:"createdAt"`
	Id         string  `json:"id"`
	Label      *string `json:"label"`
	LastUsedAt *string `json:"lastUsedAt"`
	RevokedAt  *string `json:"revokedAt"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Tokens []Token `json:"tokens"`
}

// UsageDay defines model for UsageDay.
type UsageDay struct {
	BytesIn    float32 `json:"bytesIn"`
	BytesOut   float32 `json:"bytesOut"`
	Day        string  `json:"day"`
	Requests   float32 `json:"requests"`
	TotalBytes float32 `json:"totalBytes"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	BytesIn    float32    `json:"bytesIn"`
	BytesOut   float32    `json:"bytesOut"`
	LastSeen   *string    `json:"lastSeen"`
	Requests   float32    `json:"requests"`
	Series     []UsageDay `json:"series"`
	TotalBytes float32    `json:"totalBytes"`
}

// VerifyTokenRequest defines model for VerifyTokenRequest.
type VerifyTokenRequest struct {
	Token string `json:"token"`
}

// VerifyTokenResponse defines model for VerifyTokenResponse.
type VerifyTokenResponse struct {
	Kind   *VerifyTokenResponseKind `json:"kind,omitempty"`
	Scopes *[]ScopeRef              `json:"scopes,omitempty"`
	Slug   *string                  `json:"slug,omitempty"`
	User   *string                  `json:"user,omitempty"`
}

// VerifyTokenResponseKind defines model for VerifyTokenResponse.Kind.
type VerifyTokenResponseKind string

// Workspace defines model for Workspace.
type Workspace struct {
	ExampleUrl  string `json:"exampleUrl"`
	Name        string `json:"name"`
	Provisioned bool   `json:"provisioned"`
	Slug        string `json:"slug"`
}

// ResolveHostParams defines parameters for ResolveHost.
type ResolveHostParams struct {
	Host string `form:"host" json:"host"`
}

// ScopeHostnamesParams defines parameters for ScopeHostnames.
type ScopeHostnamesParams struct {
	Slug string `form:"slug" json:"slug"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// PollDeviceTokenJSONRequestBody defines body for PollDeviceToken for application/json ContentType.
type PollDeviceTokenJSONRequestBody = DeviceTokenRequest

// IngestRequestsJSONRequestBody defines body for IngestRequests for application/json ContentType.
type IngestRequestsJSONRequestBody = RequestBatch

// VerifyTokenJSONRequestBody defines body for VerifyToken for application/json ContentType.
type VerifyTokenJSONRequestBody = VerifyTokenRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenInput
