// Package beamdapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package beamdapi

const (
	BearerAuthScopes    bearerAuthContextKey    = "bearerAuth.Scopes"
	EdgeSecretScopes    edgeSecretContextKey    = "edgeSecret.Scopes"
	SessionBearerScopes sessionBearerContextKey = "sessionBearer.Scopes"
)

// Defines values for VerifyTokenResponseKind.
const (
	Key     VerifyTokenResponseKind = "key"
	Session VerifyTokenResponseKind = "session"
)

// Valid indicates whether the value is a known member of the VerifyTokenResponseKind enum.
func (e VerifyTokenResponseKind) Valid() bool {
	switch e {
	case Key:
		return true
	case Session:
		return true
	default:
		return false
	}
}

// BeamAuthDiscovery defines model for BeamAuthDiscovery.
type BeamAuthDiscovery struct {
	DeviceCodeUrl   string `json:"device_code_url"`
	TokenUrl        string `json:"token_url"`
	VerificationUri string `json:"verification_uri"`
}

// CreateTokenInput defines model for CreateTokenInput.
type CreateTokenInput struct {
	Label *string `json:"label,omitempty"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CreatedAt string  `json:"createdAt"`
	Id        string  `json:"id"`
	Label     *string `json:"label"`
	Token     string  `json:"token"`
}

// DeviceCodeResponse defines model for DeviceCodeResponse.
type DeviceCodeResponse struct {
	DeviceCode      string  `json:"device_code"`
	ExpiresIn       int     `json:"expires_in"`
	Interval        *int    `json:"interval,omitempty"`
	UserCode        string  `json:"user_code"`
	VerificationUri *string `json:"verification_uri,omitempty"`
}

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	DeviceCode string `json:"device_code"`
}

// DeviceTokenResponse defines model for DeviceTokenResponse.
type DeviceTokenResponse struct {
	AccessToken *string     `json:"access_token,omitempty"`
	Edge        *string     `json:"edge,omitempty"`
	Error       *string     `json:"error,omitempty"`
	Scopes      *[]ScopeRef `json:"scopes,omitempty"`
}

// RevokeResult defines model for RevokeResult.
type RevokeResult struct {
	Id      string `json:"id"`
	Revoked bool   `json:"revoked"`
}

// ScopeRef defines model for ScopeRef.
type ScopeRef struct {
	Role *string `json:"role,omitempty"`
	Slug string  `json:"slug"`
}

// ScopesResponse defines model for ScopesResponse.
type ScopesResponse struct {
	Scopes []ScopeRef `json:"scopes"`
	User   *string    `json:"user,omitempty"`
}

// Token defines model for Token.
type Token struct {
	CreatedAt  string  `json:"createdAt"`
	Id         string  `json:"id"`
	Label      *string `json:"label"`
	LastUsedAt *string `json:"lastUsedAt"`
	RevokedAt  *string `json:"revokedAt"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Tokens []Token `json:"tokens"`
}

// UsageAccepted defines model for UsageAccepted.
type UsageAccepted struct {
	Ok bool `json:"ok"`
}

// UsageDay defines model for UsageDay.
type UsageDay struct {
	Bytes       float32 `json:"bytes"`
	Day         string  `json:"day"`
	PeakTunnels float32 `json:"peakTunnels"`
}

// UsageEvent defines model for UsageEvent.
type UsageEvent struct {
	ActiveTunnels int    `json:"active_tunnels"`
	Bytes         int    `json:"bytes"`
	PeriodEnd     string `json:"period_end"`
	PeriodStart   string `json:"period_start"`
	Slug          string `json:"slug"`
}

// UsageRequest defines model for UsageRequest.
type UsageRequest struct {
	Events             []UsageEvent `json:"events"`
	RequestsTotalDelta *int         `json:"requests_total_delta,omitempty"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	EventCount  float32    `json:"eventCount"`
	LastSeen    *string    `json:"lastSeen"`
	PeakTunnels float32    `json:"peakTunnels"`
	Series      []UsageDay `json:"series"`
	TotalBytes  float32    `json:"totalBytes"`
}

// VerifyTokenRequest defines model for VerifyTokenRequest.
type VerifyTokenRequest struct {
	Token string `json:"token"`
}

// VerifyTokenResponse defines model for VerifyTokenResponse.
type VerifyTokenResponse struct {
	Kind   *VerifyTokenResponseKind `json:"kind,omitempty"`
	Scopes *[]ScopeRef              `json:"scopes,omitempty"`
	Slug   *string                  `json:"slug,omitempty"`
	User   *string                  `json:"user,omitempty"`
}

// VerifyTokenResponseKind defines model for VerifyTokenResponse.Kind.
type VerifyTokenResponseKind string

// Workspace defines model for Workspace.
type Workspace struct {
	Name        string `json:"name"`
	Provisioned bool   `json:"provisioned"`
	Slug        string `json:"slug"`
	TunnelBase  string `json:"tunnelBase"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// edgeSecretContextKey is the context key for edgeSecret security scheme
type edgeSecretContextKey string

// sessionBearerContextKey is the context key for sessionBearer security scheme
type sessionBearerContextKey string

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// PollDeviceTokenJSONRequestBody defines body for PollDeviceToken for application/json ContentType.
type PollDeviceTokenJSONRequestBody = DeviceTokenRequest

// IngestUsageJSONRequestBody defines body for IngestUsage for application/json ContentType.
type IngestUsageJSONRequestBody = UsageRequest

// VerifyTokenJSONRequestBody defines body for VerifyToken for application/json ContentType.
type VerifyTokenJSONRequestBody = VerifyTokenRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenInput
